---
- name: insert iptables rule to open port 80
  lineinfile: dest=/etc/sysconfig/iptables state=present regexp="-A INPUT -p tcp -m state --state NEW -m tcp --dport 80 -j ACCEPT"
              insertbefore="^-A INPUT -j REJECT" line="-A INPUT -p tcp -m state --state NEW -m tcp --dport 80 -j ACCEPT"
- name: restart iptables
  service: name=iptables state=restarted
  notify: restart apache
  
