galaxy_info:
  author: compose 
  license: "license (BSD, MIT)"
  min_ansible_version: 1.8
  platforms:
  - name: EL
    versions:
    - 7
    galaxy_tags:     
    - firewall
    - iptables

dependencies: []
