---
# Create our config
- name: create nrpe.cfg from template
  template: >
    src="nrpe.cfg.j2"
    dest="{{ nagios_nrpe_server_dir }}/nrpe.cfg"
    owner=root group=root mode=0644
  notify: restart nagios-nrpe-server

